name: guinness2
version: 0.1.0-dev
author: Julie Ralph <ju.ralph@gmail.com>
homepage: https://github.com/juliemr/guinness2
description: A port of the Jasmine testing framework.
dependencies:
  collection: ">=1.4.0 <2.0.0"
  test: "^0.12.9"
dev_dependencies:
  mockito: "0.11.0"
environment:
  sdk: ">=1.13.0 <2.0.0"
