name: guinness2
version: 0.1.0-dev
author: Julie Ralph <ju.ralph@gmail.com>
homepage: https://github.com/juliemr/guinness2
description: A port of the Jasmine testing framework.
environment:
  sdk: ">=1.9.0 <2.0.0"
dependencies:
  collection: "^1.0.0"
  test: "^0.12.3"
dev_dependencies:
  mockito: "^0.10.1"
